#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

mv ./constant/triSurface .
mv ./constant/extendedFeatureEdgeMesh .

# Delete cellToRegion file
rm -f ./constant/cellToRegion

# Delete all subdirectories into the system and constant directories
#find ./system/*   -type d 2>/dev/null -exec rm -v -r {} \;
find ./constant/* -type d 2>/dev/null -exec rm -v -r {} \;

# Delete all time steps
rm -f log.*
cleanCase

mv ./triSurface ./constant
mv ./extendedFeatureEdgeMesh ./constant

rm -rf 0
cp -r 0.org 0

